version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "installing packages"
      - run: npm install
      - run: CI=false npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "starting test"
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test
